export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  emojis: EmojiItem[];
}

export const emojiCategories: EmojiCategory[] = [
  {
    id: 'smileys',
    name: '笑脸',
    emojis: [
      { emoji: '😀', name: '笑脸', keywords: ['开心', '高兴', '微笑', '快乐'] },
      { emoji: '😃', name: '大笑', keywords: ['开心', '高兴', '笑', '快乐'] },
      { emoji: '😄', name: '微笑', keywords: ['开心', '高兴', '笑', '快乐'] },
      { emoji: '😁', name: '露齿笑', keywords: ['开心', '高兴', '笑', '快乐'] },
      { emoji: '😆', name: '斜眼笑', keywords: ['开心', '高兴', '笑', '快乐'] },
      { emoji: '😅', name: '苦笑', keywords: ['尴尬', '汗', '紧张'] },
      { emoji: '🤣', name: '笑到哭', keywords: ['笑', '哭', '开心', '高兴'] },
      { emoji: '😂', name: '喜极而泣', keywords: ['笑', '哭', '开心', '高兴'] },
      { emoji: '🙂', name: '微笑', keywords: ['开心', '高兴', '微笑', '快乐'] },
      { emoji: '🙃', name: '倒立脸', keywords: ['搞怪', '有趣', '微笑'] },
      { emoji: '😉', name: '眨眼', keywords: ['眨眼', '开玩笑', '调情'] },
      { emoji: '😊', name: '幸福微笑', keywords: ['幸福', '开心', '微笑', '快乐'] },
      { emoji: '😇', name: '天使', keywords: ['天使', '纯洁', '无辜'] },
      { emoji: '🥰', name: '喜爱', keywords: ['爱', '喜欢', '爱心', '可爱'] },
      { emoji: '😍', name: '花痴', keywords: ['爱', '喜欢', '爱心', '可爱'] },
      { emoji: '🤩', name: '星星眼', keywords: ['喜欢', '星星', '兴奋'] },
      { emoji: '😘', name: '飞吻', keywords: ['爱', '亲吻', '飞吻'] },
      { emoji: '😗', name: '亲吻', keywords: ['爱', '亲吻', '亲吻'] },
      { emoji: '☺️', name: '害羞微笑', keywords: ['害羞', '微笑', '开心'] },
      { emoji: '😚', name: '微笑亲吻', keywords: ['爱', '亲吻', '微笑'] },
      { emoji: '😙', name: '亲吻', keywords: ['爱', '亲吻', '亲吻'] },
      { emoji: '🥲', name: '含泪微笑', keywords: ['哭', '微笑', '感动'] },
      { emoji: '😋', name: '舔嘴唇', keywords: ['好吃', '美味', '饿'] },
      { emoji: '😛', name: '吐舌头', keywords: ['调皮', '开玩笑', '吐舌头'] },
      { emoji: '😜', name: '眨眼吐舌', keywords: ['调皮', '开玩笑', '吐舌头'] },
      { emoji: '🤪', name: '疯狂', keywords: ['疯狂', '疯了', '搞怪'] },
      { emoji: '😝', name: '眯眼吐舌', keywords: ['调皮', '开玩笑', '吐舌头'] },
      { emoji: '🤑', name: '发财', keywords: ['钱', '财富', '发财'] },
      { emoji: '🤗', name: '拥抱', keywords: ['拥抱', '温暖', '友好'] },
      { emoji: '🤭', name: '捂嘴笑', keywords: ['笑', '害羞', '尴尬'] },
      { emoji: '🤫', name: '嘘', keywords: ['安静', '保密', '嘘'] },
      { emoji: '🤔', name: '思考', keywords: ['思考', '想', '考虑'] },
      { emoji: '🤐', name: '闭嘴', keywords: ['闭嘴', '不说', '保密'] },
      { emoji: '🤨', name: '挑眉', keywords: ['怀疑', '思考', '疑惑'] },
      { emoji: '😐', name: '面无表情', keywords: ['面无表情', '冷漠', '中性'] },
      { emoji: '😑', name: '面无表情', keywords: ['面无表情', '冷漠', '中性'] },
      { emoji: '😶', name: '沉默', keywords: ['沉默', '无语', '不说'] },
      { emoji: '😏', name: '得意', keywords: ['得意', '狡猾', '自信'] },
      { emoji: '😒', name: '不高兴', keywords: ['不高兴', '生气', '难过'] },
      { emoji: '🙄', name: '翻白眼', keywords: ['无聊', '无语', '翻白眼'] },
      { emoji: '😬', name: '龇牙', keywords: ['尴尬', '紧张', '害怕'] },
      { emoji: '🤥', name: '匹诺曹', keywords: ['说谎', '骗子', '不诚实'] },
      { emoji: '😌', name: '如释重负', keywords: ['放松', '如释重负', '平静'] },
      { emoji: '😔', name: '难过', keywords: ['难过', '伤心', '悲伤'] },
      { emoji: '😪', name: '困倦', keywords: ['困', '睡觉', '疲倦'] },
      { emoji: '🤤', name: '流口水', keywords: ['好吃', '饿', '流口水'] },
      { emoji: '😴', name: '睡觉', keywords: ['睡觉', '困', '休息'] },
      { emoji: '😷', name: '口罩', keywords: ['生病', '口罩', '健康'] },
      { emoji: '🤒', name: '发烧', keywords: ['生病', '发烧', '感冒'] },
      { emoji: '🤕', name: '受伤', keywords: ['受伤', '疼痛', '绷带'] },
      { emoji: '🤢', name: '恶心', keywords: ['恶心', '吐', '不舒服'] },
      { emoji: '🤮', name: '呕吐', keywords: ['呕吐', '吐', '恶心'] },
      { emoji: '🤧', name: '打喷嚏', keywords: ['感冒', '打喷嚏', '过敏'] },
      { emoji: '🥵', name: '热', keywords: ['热', '出汗', '温度'] },
      { emoji: '🥶', name: '冷', keywords: ['冷', '冻', '温度'] },
      { emoji: '🥴', name: '头晕', keywords: ['头晕', '醉', '晕'] },
      { emoji: '😵', name: '晕', keywords: ['晕', '晕倒', '震惊'] },
      { emoji: '🤯', name: '爆炸头', keywords: ['震惊', '爆炸', '惊讶'] },
      { emoji: '🤠', name: '牛仔', keywords: ['牛仔', '西部', '帽子'] },
      { emoji: '🥳', name: '派对', keywords: ['派对', '庆祝', '开心'] },
      { emoji: '🥸', name: '伪装', keywords: ['伪装', '侦探', '眼镜'] },
      { emoji: '😎', name: '墨镜', keywords: ['酷', '墨镜', '时尚'] },
      { emoji: '🤓', name: '书呆子', keywords: ['书呆子', '聪明', '眼镜'] },
      { emoji: '🧐', name: '单片眼镜', keywords: ['思考', '疑惑', '眼镜'] },
      { emoji: '😕', name: '困惑', keywords: ['困惑', '疑惑', '不确定'] },
      { emoji: '😟', name: '担心', keywords: ['担心', '焦虑', '不安'] },
      { emoji: '🙁', name: '难过', keywords: ['难过', '伤心', '悲伤'] },
      { emoji: '☹️', name: '难过', keywords: ['难过', '伤心', '悲伤'] },
      { emoji: '😮', name: '惊讶', keywords: ['惊讶', '震惊', '意外'] },
      { emoji: '😯', name: '惊讶', keywords: ['惊讶', '震惊', '意外'] },
      { emoji: '😲', name: '震惊', keywords: ['震惊', '惊讶', '意外'] },
      { emoji: '😳', name: '脸红', keywords: ['脸红', '害羞', '尴尬'] },
      { emoji: '🥺', name: '恳求', keywords: ['恳求', '可爱', '眼睛'] },
      { emoji: '😦', name: '皱眉张嘴', keywords: ['惊讶', '震惊', '意外'] },
      { emoji: '😧', name: '痛苦', keywords: ['痛苦', '难过', '惊讶'] },
      { emoji: '😨', name: '害怕', keywords: ['害怕', '恐惧', '担心'] },
      { emoji: '😰', name: '冷汗', keywords: ['紧张', '害怕', '汗'] },
      { emoji: '😥', name: '失望', keywords: ['失望', '难过', '汗'] },
      { emoji: '😢', name: '哭', keywords: ['哭', '伤心', '难过'] },
      { emoji: '😭', name: '大哭', keywords: ['哭', '伤心', '难过'] },
      { emoji: '😱', name: '尖叫', keywords: ['害怕', '尖叫', '恐惧'] },
      { emoji: '😖', name: '困扰', keywords: ['困扰', '难过', '不安'] },
      { emoji: '😣', name: '忍耐', keywords: ['忍耐', '坚持', '困难'] },
      { emoji: '😞', name: '失望', keywords: ['失望', '难过', '伤心'] },
      { emoji: '😓', name: '汗', keywords: ['紧张', '汗', '尴尬'] },
      { emoji: '😩', name: '疲惫', keywords: ['疲惫', '累', '辛苦'] },
      { emoji: '😫', name: '累', keywords: ['累', '疲惫', '辛苦'] },
      { emoji: '🥱', name: '打哈欠', keywords: ['困', '累', '打哈欠'] },
      { emoji: '😤', name: '生气', keywords: ['生气', '愤怒', '脾气'] },
      { emoji: '😡', name: '愤怒', keywords: ['生气', '愤怒', '脾气'] },
      { emoji: '😠', name: '生气', keywords: ['生气', '愤怒', '脾气'] },
      { emoji: '🤬', name: '骂人', keywords: ['生气', '骂人', '愤怒'] },
      { emoji: '😈', name: '恶魔', keywords: ['恶魔', '坏', '邪恶'] },
      { emoji: '👿', name: '小恶魔', keywords: ['恶魔', '坏', '邪恶'] },
      { emoji: '💀', name: '骷髅', keywords: ['骷髅', '死', '万圣节'] },
      { emoji: '☠️', name: '骷髅', keywords: ['骷髅', '死', '万圣节'] },
      { emoji: '💩', name: '便便', keywords: ['便便', '屎', '搞笑'] },
      { emoji: '👻', name: '幽灵', keywords: ['幽灵', '鬼', '万圣节'] },
      { emoji: '👽', name: '外星人', keywords: ['外星人', 'UFO', '太空'] },
      { emoji: '👾', name: '怪物', keywords: ['怪物', '游戏', '像素'] },
      { emoji: '🤖', name: '机器人', keywords: ['机器人', 'AI', '科技'] },
      { emoji: '🎃', name: '南瓜', keywords: ['南瓜', '万圣节', '节日'] },
      { emoji: '😺', name: '笑猫', keywords: ['猫', '动物', '笑'] },
      { emoji: '😸', name: '开心猫', keywords: ['猫', '动物', '开心'] },
      { emoji: '😹', name: '哭笑脸猫', keywords: ['猫', '动物', '笑', '哭'] },
      { emoji: '😻', name: '爱心眼猫', keywords: ['猫', '动物', '爱', '喜欢'] },
      { emoji: '😼', name: '得意猫', keywords: ['猫', '动物', '得意'] },
      { emoji: '😽', name: '亲吻猫', keywords: ['猫', '动物', '爱', '亲吻'] },
      { emoji: '🙀', name: '惊讶猫', keywords: ['猫', '动物', '惊讶'] },
      { emoji: '😿', name: '哭猫', keywords: ['猫', '动物', '哭', '难过'] },
      { emoji: '😾', name: '生气猫', keywords: ['猫', '动物', '生气'] },
    ],
  },
  {
    id: 'gestures',
    name: '手势',
    emojis: [
      { emoji: '👋', name: '挥手', keywords: ['你好', '再见', '打招呼', '挥手'] },
      { emoji: '🤚', name: '手掌', keywords: ['手', '手掌', '停止'] },
      { emoji: '🖐️', name: '手掌', keywords: ['手', '手掌', '停止'] },
      { emoji: '✋', name: '手掌', keywords: ['手', '手掌', '停止'] },
      { emoji: '🖖', name: '瓦肯举手礼', keywords: ['手', '星际迷航', '问候'] },
      { emoji: '👌', name: 'OK', keywords: ['好的', '没问题', 'OK'] },
      { emoji: '🤌', name: '捏手指', keywords: ['手', '捏', '意大利'] },
      { emoji: '🤏', name: '捏', keywords: ['小', '捏', '一点点'] },
      { emoji: '✌️', name: '胜利', keywords: ['胜利', 'V字', '和平'] },
      { emoji: '🤞', name: '交叉手指', keywords: ['幸运', '希望', '祈祷'] },
      { emoji: '🤟', name: '爱你', keywords: ['爱', '摇滚', '手势'] },
      { emoji: '🤘', name: '摇滚', keywords: ['摇滚', '音乐', '手势'] },
      { emoji: '🤙', name: '打电话', keywords: ['电话', '联系', '手势'] },
      { emoji: '👈', name: '左指', keywords: ['左边', '指', '方向'] },
      { emoji: '👉', name: '右指', keywords: ['右边', '指', '方向'] },
      { emoji: '👆', name: '上指', keywords: ['上面', '指', '方向'] },
      { emoji: '🖕', name: '中指', keywords: ['中指', '粗鲁', '生气'] },
      { emoji: '👇', name: '下指', keywords: ['下面', '指', '方向'] },
      { emoji: '☝️', name: '上指', keywords: ['上面', '指', '方向'] },
      { emoji: '👍', name: '点赞', keywords: ['好', '棒', '喜欢', '赞同'] },
      { emoji: '👎', name: '踩', keywords: ['坏', '不喜欢', '不赞同'] },
      { emoji: '👊', name: '拳头', keywords: ['拳头', '打', '力量'] },
      { emoji: '🤛', name: '左拳', keywords: ['拳头', '左', '力量'] },
      { emoji: '🤜', name: '右拳', keywords: ['拳头', '右', '力量'] },
      { emoji: '👏', name: '鼓掌', keywords: ['鼓掌', '好', '棒', '庆祝'] },
      { emoji: '🙌', name: '举手', keywords: ['开心', '庆祝', '胜利'] },
      { emoji: '👐', name: '张开手', keywords: ['张开', '手', '拥抱'] },
      { emoji: '🤲', name: '掌心向上', keywords: ['手', '向上', '祈祷'] },
      { emoji: '🤝', name: '握手', keywords: ['握手', '你好', '合作'] },
      { emoji: '🙏', name: '祈祷', keywords: ['祈祷', '感谢', '请求'] },
      { emoji: '✍️', name: '写字', keywords: ['写', '字', '笔记'] },
      { emoji: '💅', name: '涂指甲油', keywords: ['美甲', '指甲', '美容'] },
      { emoji: '🤳', name: '自拍', keywords: ['自拍', '手机', '拍照'] },
      { emoji: '💪', name: '肌肉', keywords: ['肌肉', '强壮', '健身'] },
      { emoji: '🦾', name: '机械臂', keywords: ['机械', '机器人', '强壮'] },
      { emoji: '🦿', name: '机械腿', keywords: ['机械', '机器人', '腿'] },
      { emoji: '🦵', name: '腿', keywords: ['腿', '脚', '走路'] },
      { emoji: '🦶', name: '脚', keywords: ['脚', '走路', '踢'] },
      { emoji: '👂', name: '耳朵', keywords: ['耳朵', '听', '声音'] },
      { emoji: '🦻', name: '戴助听器', keywords: ['耳朵', '助听器', '听'] },
      { emoji: '👃', name: '鼻子', keywords: ['鼻子', '闻', '嗅觉'] },
      { emoji: '👀', name: '眼睛', keywords: ['眼睛', '看', '观察'] },
      { emoji: '👁️', name: '眼睛', keywords: ['眼睛', '看', '观察'] },
      { emoji: '👅', name: '舌头', keywords: ['舌头', '舔', '尝'] },
      { emoji: '👄', name: '嘴', keywords: ['嘴', '说话', '亲吻'] },
      { emoji: '🫀', name: '心脏', keywords: ['心脏', '器官', '爱'] },
      { emoji: '🫁', name: '肺', keywords: ['肺', '器官', '呼吸'] },
      { emoji: '🧠', name: '大脑', keywords: ['大脑', '思考', '智能'] },
      { emoji: '🦷', name: '牙齿', keywords: ['牙齿', '牙', '口腔'] },
      { emoji: '🦴', name: '骨头', keywords: ['骨头', '骨骼', '身体'] },
      { emoji: '👶', name: '婴儿', keywords: ['婴儿', '宝宝', '小孩'] },
      { emoji: '🧒', name: '儿童', keywords: ['儿童', '小孩', '年轻'] },
      { emoji: '👦', name: '男孩', keywords: ['男孩', '小孩', '年轻'] },
      { emoji: '👧', name: '女孩', keywords: ['女孩', '小孩', '年轻'] },
      { emoji: '🧑', name: '人', keywords: ['人', '成人', '中性'] },
      { emoji: '👱', name: '金发人', keywords: ['金发', '人', '头发'] },
      { emoji: '👨', name: '男人', keywords: ['男人', '成人', '男性'] },
      { emoji: '🧔', name: '有胡子的人', keywords: ['胡子', '人', '男性'] },
      { emoji: '👩', name: '女人', keywords: ['女人', '成人', '女性'] },
      { emoji: '🧓', name: '老人', keywords: ['老人', '老年', '祖父母'] },
      { emoji: '👴', name: '老爷爷', keywords: ['爷爷', '老人', '男性'] },
      { emoji: '👵', name: '老奶奶', keywords: ['奶奶', '老人', '女性'] },
      { emoji: '🙍', name: '皱眉', keywords: ['难过', '担心', '生气'] },
      { emoji: '🙎', name: '撅嘴', keywords: ['生气', '不高兴', '撅嘴'] },
      { emoji: '🙅', name: '不行', keywords: ['不行', '拒绝', '不要'] },
      { emoji: '🙆', name: 'OK', keywords: ['好的', '同意', '没问题'] },
      { emoji: '💁', name: '服务', keywords: ['服务', '帮助', '信息'] },
      { emoji: '🙋', name: '举手', keywords: ['举手', '问', '回答'] },
      { emoji: '🧏', name: '失聪', keywords: ['聋', '听', '手势'] },
      { emoji: '🙇', name: '鞠躬', keywords: ['鞠躬', '道歉', '感谢'] },
      { emoji: '🤦', name: '捂脸', keywords: ['无语', '尴尬', '失望'] },
      { emoji: '🤷', name: '耸肩', keywords: ['不知道', '耸肩', '无所谓'] },
      { emoji: '🧑‍⚕️', name: '医生', keywords: ['医生', '健康', '医院'] },
      { emoji: '👨‍⚕️', name: '男医生', keywords: ['医生', '健康', '医院', '男性'] },
      { emoji: '👩‍⚕️', name: '女医生', keywords: ['医生', '健康', '医院', '女性'] },
      { emoji: '🧑‍🎓', name: '学生', keywords: ['学生', '学校', '学习'] },
      { emoji: '👨‍🎓', name: '男学生', keywords: ['学生', '学校', '学习', '男性'] },
      { emoji: '👩‍🎓', name: '女学生', keywords: ['学生', '学校', '学习', '女性'] },
      { emoji: '🧑‍🏫', name: '老师', keywords: ['老师', '学校', '教育'] },
      { emoji: '👨‍🏫', name: '男老师', keywords: ['老师', '学校', '教育', '男性'] },
      { emoji: '👩‍🏫', name: '女老师', keywords: ['老师', '学校', '教育', '女性'] },
      { emoji: '🧑‍⚖️', name: '法官', keywords: ['法官', '法律', '法院'] },
      { emoji: '👨‍⚖️', name: '男法官', keywords: ['法官', '法律', '法院', '男性'] },
      { emoji: '👩‍⚖️', name: '女法官', keywords: ['法官', '法律', '法院', '女性'] },
      { emoji: '🧑‍🌾', name: '农民', keywords: ['农民', '农场', '农业'] },
      { emoji: '👨‍🌾', name: '男农民', keywords: ['农民', '农场', '农业', '男性'] },
      { emoji: '👩‍🌾', name: '女农民', keywords: ['农民', '农场', '农业', '女性'] },
      { emoji: '🧑‍🍳', name: '厨师', keywords: ['厨师', '厨房', '食物'] },
      { emoji: '👨‍🍳', name: '男厨师', keywords: ['厨师', '厨房', '食物', '男性'] },
      { emoji: '👩‍🍳', name: '女厨师', keywords: ['厨师', '厨房', '食物', '女性'] },
      { emoji: '🧑‍🔧', name: '技工', keywords: ['技工', '修理', '工具'] },
      { emoji: '👨‍🔧', name: '男技工', keywords: ['技工', '修理', '工具', '男性'] },
      { emoji: '👩‍🔧', name: '女技工', keywords: ['技工', '修理', '工具', '女性'] },
      { emoji: '🧑‍🏭', name: '工人', keywords: ['工人', '工厂', '工作'] },
      { emoji: '👨‍🏭', name: '男工人', keywords: ['工人', '工厂', '工作', '男性'] },
      { emoji: '👩‍🏭', name: '女工人', keywords: ['工人', '工厂', '工作', '女性'] },
      { emoji: '🧑‍💼', name: '上班族', keywords: ['上班族', '办公室', '工作'] },
      { emoji: '👨‍💼', name: '男上班族', keywords: ['上班族', '办公室', '工作', '男性'] },
      { emoji: '👩‍💼', name: '女上班族', keywords: ['上班族', '办公室', '工作', '女性'] },
      { emoji: '🧑‍🔬', name: '科学家', keywords: ['科学家', '实验室', '研究'] },
      { emoji: '👨‍🔬', name: '男科学家', keywords: ['科学家', '实验室', '研究', '男性'] },
      { emoji: '👩‍🔬', name: '女科学家', keywords: ['科学家', '实验室', '研究', '女性'] },
      { emoji: '🧑‍💻', name: '程序员', keywords: ['程序员', '电脑', '科技'] },
      { emoji: '👨‍💻', name: '男程序员', keywords: ['程序员', '电脑', '科技', '男性'] },
      { emoji: '👩‍💻', name: '女程序员', keywords: ['程序员', '电脑', '科技', '女性'] },
      { emoji: '🧑‍🎤', name: '歌手', keywords: ['歌手', '音乐', '表演'] },
      { emoji: '👨‍🎤', name: '男歌手', keywords: ['歌手', '音乐', '表演', '男性'] },
      { emoji: '👩‍🎤', name: '女歌手', keywords: ['歌手', '音乐', '表演', '女性'] },
      { emoji: '🧑‍🎨', name: '艺术家', keywords: ['艺术家', '艺术', '绘画'] },
      { emoji: '👨‍🎨', name: '男艺术家', keywords: ['艺术家', '艺术', '绘画', '男性'] },
      { emoji: '👩‍🎨', name: '女艺术家', keywords: ['艺术家', '艺术', '绘画', '女性'] },
      { emoji: '🧑‍✈️', name: '飞行员', keywords: ['飞行员', '飞机', '旅行'] },
      { emoji: '👨‍✈️', name: '男飞行员', keywords: ['飞行员', '飞机', '旅行', '男性'] },
      { emoji: '👩‍✈️', name: '女飞行员', keywords: ['飞行员', '飞机', '旅行', '女性'] },
      { emoji: '🧑‍🚀', name: '宇航员', keywords: ['宇航员', '太空', '火箭'] },
      { emoji: '👨‍🚀', name: '男宇航员', keywords: ['宇航员', '太空', '火箭', '男性'] },
      { emoji: '👩‍🚀', name: '女宇航员', keywords: ['宇航员', '太空', '火箭', '女性'] },
      { emoji: '🧑‍🚒', name: '消防员', keywords: ['消防员', '救火', '安全'] },
      { emoji: '👨‍🚒', name: '男消防员', keywords: ['消防员', '救火', '安全', '男性'] },
      { emoji: '👩‍🚒', name: '女消防员', keywords: ['消防员', '救火', '安全', '女性'] },
      { emoji: '👮', name: '警察', keywords: ['警察', '安全', '法律'] },
      { emoji: '💂', name: '卫兵', keywords: ['卫兵', '守卫', '皇家'] },
      { emoji: '🕵️', name: '侦探', keywords: ['侦探', '间谍', '调查'] },
      { emoji: '💃', name: '跳舞', keywords: ['跳舞', '派对', '开心'] },
      { emoji: '🕺', name: '男人跳舞', keywords: ['跳舞', '派对', '开心'] },
      { emoji: '👯', name: '兔女郎', keywords: ['跳舞', '派对', '朋友'] },
      { emoji: '🧖', name: '桑拿', keywords: ['桑拿', '放松', '温泉'] },
      { emoji: '🧗', name: '攀岩', keywords: ['攀岩', '爬山', '运动'] },
      { emoji: '🏌️', name: '高尔夫', keywords: ['高尔夫', '运动', '球'] },
      { emoji: '🏄', name: '冲浪', keywords: ['冲浪', '海洋', '运动'] },
      { emoji: '🏊', name: '游泳', keywords: ['游泳', '运动', '水'] },
      { emoji: '⛹️', name: '打球', keywords: ['球', '运动', '篮球'] },
      { emoji: '🏋️', name: '举重', keywords: ['举重', '健身', '运动'] },
      { emoji: '🚴', name: '骑自行车', keywords: ['自行车', '运动', '骑'] },
      { emoji: '🚵', name: '骑山地车', keywords: ['自行车', '运动', '山地'] },
      { emoji: '🤸', name: '侧手翻', keywords: ['体操', '运动', '翻'] },
      { emoji: '🤽', name: '水球', keywords: ['水球', '运动', '球'] },
      { emoji: '🤾', name: '手球', keywords: ['手球', '运动', '球'] },
      { emoji: '🤹', name: '杂耍', keywords: ['杂耍', '表演', '球'] },
      { emoji: '🧘', name: '冥想', keywords: ['冥想', '瑜伽', '放松'] },
      { emoji: '🛀', name: '洗澡', keywords: ['洗澡', '清洁', '放松'] },
      { emoji: '🛌', name: '睡觉', keywords: ['睡觉', '休息', '床'] },
      { emoji: '👭', name: '两个女人', keywords: ['女人', '朋友', '一起'] },
      { emoji: '👫', name: '男女', keywords: ['男人', '女人', '情侣'] },
      { emoji: '👬', name: '两个男人', keywords: ['男人', '朋友', '一起'] },
      { emoji: '💏', name: '亲吻', keywords: ['爱', '亲吻', '情侣'] },
      { emoji: '💑', name: '情侣', keywords: ['爱', '情侣', '一起'] },
      { emoji: '👪', name: '家庭', keywords: ['家庭', '一起', '父母'] },
    ],
  },
  {
    id: 'animals',
    name: '动物',
    emojis: [
      { emoji: '🐵', name: '猴子脸', keywords: ['猴子', '动物', '脸'] },
      { emoji: '🙈', name: '非礼勿视', keywords: ['猴子', '看', '眼睛'] },
      { emoji: '🙉', name: '非礼勿听', keywords: ['猴子', '听', '耳朵'] },
      { emoji: '🙊', name: '非礼勿言', keywords: ['猴子', '说话', '嘴'] },
      { emoji: '🐒', name: '猴子', keywords: ['猴子', '动物'] },
      { emoji: '🦍', name: '大猩猩', keywords: ['猩猩', '动物', '黑'] },
      { emoji: '🦧', name: '红毛猩猩', keywords: ['猩猩', '动物', '红'] },
      { emoji: '🐶', name: '狗脸', keywords: ['狗', '动物', '宠物'] },
      { emoji: '🐕', name: '狗', keywords: ['狗', '动物', '宠物'] },
      { emoji: '🦮', name: '导盲犬', keywords: ['狗', '导盲', '服务'] },
      { emoji: '🐕‍🦺', name: '服务犬', keywords: ['狗', '服务', '帮助'] },
      { emoji: '🐩', name: '贵宾犬', keywords: ['狗', '贵宾', '宠物'] },
      { emoji: '🐺', name: '狼', keywords: ['狼', '动物', '野生'] },
      { emoji: '🦊', name: '狐狸', keywords: ['狐狸', '动物', '狡猾'] },
      { emoji: '🦝', name: '浣熊', keywords: ['浣熊', '动物', '小'] },
      { emoji: '🐱', name: '猫脸', keywords: ['猫', '动物', '宠物'] },
      { emoji: '🐈', name: '猫', keywords: ['猫', '动物', '宠物'] },
      { emoji: '🐈‍⬛', name: '黑猫', keywords: ['猫', '黑', '宠物'] },
      { emoji: '🦁', name: '狮子', keywords: ['狮子', '动物', '国王'] },
      { emoji: '🐯', name: '老虎', keywords: ['老虎', '动物', '野生'] },
      { emoji: '🐅', name: '老虎', keywords: ['老虎', '动物', '野生'] },
      { emoji: '🐆', name: '豹子', keywords: ['豹子', '动物', '野生'] },
      { emoji: '🐴', name: '马脸', keywords: ['马', '动物', '骑'] },
      { emoji: '🫎', name: '驼鹿', keywords: ['驼鹿', '动物', '野生'] },
      { emoji: '🫏', name: '驴', keywords: ['驴', '动物', '农场'] },
      { emoji: '🐎', name: '马', keywords: ['马', '动物', '骑'] },
      { emoji: '🦄', name: '独角兽', keywords: ['独角兽', '神话', '魔法'] },
      { emoji: '🦓', name: '斑马', keywords: ['斑马', '动物', '条纹'] },
      { emoji: '🦌', name: '鹿', keywords: ['鹿', '动物', '野生'] },
      { emoji: '🦬', name: '野牛', keywords: ['野牛', '动物', '野生'] },
      { emoji: '🐮', name: '牛脸', keywords: ['牛', '动物', '农场'] },
      { emoji: '🐂', name: '公牛', keywords: ['公牛', '动物', '农场'] },
      { emoji: '🐃', name: '水牛', keywords: ['水牛', '动物', '农场'] },
      { emoji: '🐄', name: '奶牛', keywords: ['奶牛', '动物', '牛奶'] },
      { emoji: '🐷', name: '猪脸', keywords: ['猪', '动物', '农场'] },
      { emoji: '🐖', name: '猪', keywords: ['猪', '动物', '农场'] },
      { emoji: '🐗', name: '野猪', keywords: ['野猪', '动物', '野生'] },
      { emoji: '🐽', name: '猪鼻子', keywords: ['猪', '鼻子', '动物'] },
      { emoji: '🐏', name: '公羊', keywords: ['羊', '动物', '农场'] },
      { emoji: '🐑', name: '绵羊', keywords: ['绵羊', '动物', '羊毛'] },
      { emoji: '🐐', name: '山羊', keywords: ['山羊', '动物', '农场'] },
      { emoji: '🐪', name: '骆驼', keywords: ['骆驼', '动物', '沙漠'] },
      { emoji: '🐫', name: '双峰驼', keywords: ['骆驼', '动物', '沙漠'] },
      { emoji: '🦙', name: '羊驼', keywords: ['羊驼', '动物', '可爱'] },
      { emoji: '🦒', name: '长颈鹿', keywords: ['长颈鹿', '动物', '高'] },
      { emoji: '🐘', name: '大象', keywords: ['大象', '动物', '大'] },
      { emoji: '🦣', name: '猛犸象', keywords: ['猛犸象', '动物', '史前'] },
      { emoji: '🦏', name: '犀牛', keywords: ['犀牛', '动物', '野生'] },
      { emoji: '🦛', name: '河马', keywords: ['河马', '动物', '野生'] },
      { emoji: '🐭', name: '老鼠脸', keywords: ['老鼠', '动物', '小'] },
      { emoji: '🐁', name: '老鼠', keywords: ['老鼠', '动物', '小'] },
      { emoji: '🐀', name: '大鼠', keywords: ['大鼠', '动物', '小'] },
      { emoji: '🐹', name: '仓鼠', keywords: ['仓鼠', '动物', '宠物'] },
      { emoji: '🐰', name: '兔子脸', keywords: ['兔子', '动物', '可爱'] },
      { emoji: '🐇', name: '兔子', keywords: ['兔子', '动物', '可爱'] },
      { emoji: '🐿️', name: '松鼠', keywords: ['松鼠', '动物', '坚果'] },
      { emoji: '🦫', name: '海狸', keywords: ['海狸', '动物', '水'] },
      { emoji: '🦔', name: '刺猬', keywords: ['刺猬', '动物', '小'] },
      { emoji: '🦇', name: '蝙蝠', keywords: ['蝙蝠', '动物', '夜间'] },
      { emoji: '🐻', name: '熊', keywords: ['熊', '动物', '野生'] },
      { emoji: '🐨', name: '考拉', keywords: ['考拉', '动物', '可爱'] },
      { emoji: '🐼', name: '熊猫', keywords: ['熊猫', '动物', '中国'] },
      { emoji: '🦥', name: '树懒', keywords: ['树懒', '动物', '慢'] },
      { emoji: '🦦', name: '水獭', keywords: ['水獭', '动物', '水'] },
      { emoji: '🦨', name: '臭鼬', keywords: ['臭鼬', '动物', '臭'] },
      { emoji: '🦘', name: '袋鼠', keywords: ['袋鼠', '动物', '澳大利亚'] },
      { emoji: '🦡', name: '獾', keywords: ['獾', '动物', '野生'] },
      { emoji: '🐾', name: '爪印', keywords: ['爪印', '动物', '脚印'] },
      { emoji: '🦃', name: '火鸡', keywords: ['火鸡', '鸟', '食物'] },
      { emoji: '🐔', name: '鸡', keywords: ['鸡', '鸟', '农场'] },
      { emoji: '🐓', name: '公鸡', keywords: ['公鸡', '鸟', '农场'] },
      { emoji: '🐣', name: '小鸡破壳', keywords: ['小鸡', '鸟', '蛋'] },
      { emoji: '🐤', name: '小鸡', keywords: ['小鸡', '鸟', '可爱'] },
      { emoji: '🐥', name: '小鸡', keywords: ['小鸡', '鸟', '可爱'] },
      { emoji: '🐦', name: '鸟', keywords: ['鸟', '动物', '飞'] },
      { emoji: '🐧', name: '企鹅', keywords: ['企鹅', '鸟', '南极'] },
      { emoji: '🕊️', name: '鸽子', keywords: ['鸽子', '鸟', '和平'] },
      { emoji: '🦅', name: '鹰', keywords: ['鹰', '鸟', '猛禽'] },
      { emoji: '🦆', name: '鸭子', keywords: ['鸭子', '鸟', '水'] },
      { emoji: '🦢', name: '天鹅', keywords: ['天鹅', '鸟', '优雅'] },
      { emoji: '🦉', name: '猫头鹰', keywords: ['猫头鹰', '鸟', '智慧'] },
      { emoji: '🦤', name: '渡渡鸟', keywords: ['渡渡鸟', '鸟', '灭绝'] },
      { emoji: '🪶', name: '羽毛', keywords: ['羽毛', '鸟', '轻'] },
      { emoji: '🦩', name: '火烈鸟', keywords: ['火烈鸟', '鸟', '粉红'] },
      { emoji: '🦚', name: '孔雀', keywords: ['孔雀', '鸟', '美丽'] },
      { emoji: '🦜', name: '鹦鹉', keywords: ['鹦鹉', '鸟', '说话'] },
      { emoji: '🐸', name: '青蛙', keywords: ['青蛙', '动物', '绿'] },
      { emoji: '🐢', name: '乌龟', keywords: ['乌龟', '动物', '慢'] },
      { emoji: '🐊', name: '鳄鱼', keywords: ['鳄鱼', '动物', '危险'] },
      { emoji: '🦎', name: '蜥蜴', keywords: ['蜥蜴', '动物', '爬行动物'] },
      { emoji: '🐍', name: '蛇', keywords: ['蛇', '动物', '危险'] },
      { emoji: '🪱', name: '蠕虫', keywords: ['蠕虫', '动物', '小'] },
      { emoji: '🐉', name: '龙', keywords: ['龙', '神话', '魔法'] },
      { emoji: '🐲', name: '龙脸', keywords: ['龙', '神话', '魔法'] },
      { emoji: '🦕', name: '恐龙', keywords: ['恐龙', '动物', '史前'] },
      { emoji: '🦖', name: '霸王龙', keywords: ['恐龙', '动物', '史前'] },
      { emoji: '🐙', name: '章鱼', keywords: ['章鱼', '海洋', '触手'] },
      { emoji: '🦑', name: '鱿鱼', keywords: ['鱿鱼', '海洋', '触手'] },
      { emoji: '🦐', name: '虾', keywords: ['虾', '海洋', '食物'] },
      { emoji: '🦞', name: '龙虾', keywords: ['龙虾', '海洋', '食物'] },
      { emoji: '🦀', name: '螃蟹', keywords: ['螃蟹', '海洋', '红'] },
      { emoji: '🪼', name: '水母', keywords: ['水母', '海洋', '透明'] },
      { emoji: '🐚', name: '贝壳', keywords: ['贝壳', '海洋', '海滩'] },
      { emoji: '🐌', name: '蜗牛', keywords: ['蜗牛', '动物', '慢'] },
      { emoji: '🦋', name: '蝴蝶', keywords: ['蝴蝶', '昆虫', '美丽'] },
      { emoji: '🐛', name: '毛毛虫', keywords: ['毛毛虫', '昆虫', '小'] },
      { emoji: '🐜', name: '蚂蚁', keywords: ['蚂蚁', '昆虫', '小'] },
      { emoji: '🐝', name: '蜜蜂', keywords: ['蜜蜂', '昆虫', '蜂蜜'] },
      { emoji: '🪲', name: '甲虫', keywords: ['甲虫', '昆虫', '小'] },
      { emoji: '🐞', name: '瓢虫', keywords: ['瓢虫', '昆虫', '可爱'] },
      { emoji: '🦗', name: '蟋蟀', keywords: ['蟋蟀', '昆虫', '叫'] },
      { emoji: '🪳', name: '蟑螂', keywords: ['蟑螂', '昆虫', '害虫'] },
      { emoji: '🦟', name: '蚊子', keywords: ['蚊子', '昆虫', '咬'] },
      { emoji: '🪰', name: '苍蝇', keywords: ['苍蝇', '昆虫', '飞'] },
      { emoji: '🦂', name: '蝎子', keywords: ['蝎子', '动物', '危险'] },
      { emoji: '🕷️', name: '蜘蛛', keywords: ['蜘蛛', '动物', '网'] },
      { emoji: '🕸️', name: '蜘蛛网', keywords: ['蜘蛛网', '蜘蛛', '网'] },
      { emoji: '🦠', name: '微生物', keywords: ['微生物', '细菌', '小'] },
    ],
  },
  {
    id: 'food',
    name: '食物',
    emojis: [
      { emoji: '🍇', name: '葡萄', keywords: ['葡萄', '水果', '紫色'] },
      { emoji: '🍈', name: '甜瓜', keywords: ['甜瓜', '水果', '绿色'] },
      { emoji: '🍉', name: '西瓜', keywords: ['西瓜', '水果', '夏天'] },
      { emoji: '🍊', name: '橙子', keywords: ['橙子', '水果', '橙色'] },
      { emoji: '🍋', name: '柠檬', keywords: ['柠檬', '水果', '酸'] },
      { emoji: '🍌', name: '香蕉', keywords: ['香蕉', '水果', '黄色'] },
      { emoji: '🍍', name: '菠萝', keywords: ['菠萝', '水果', '热带'] },
      { emoji: '🥭', name: '芒果', keywords: ['芒果', '水果', '热带'] },
      { emoji: '🍎', name: '红苹果', keywords: ['苹果', '水果', '红色'] },
      { emoji: '🍏', name: '青苹果', keywords: ['苹果', '水果', '绿色'] },
      { emoji: '🍐', name: '梨', keywords: ['梨', '水果', '黄色'] },
      { emoji: '🍑', name: '桃子', keywords: ['桃子', '水果', '粉色'] },
      { emoji: '🍒', name: '樱桃', keywords: ['樱桃', '水果', '红色'] },
      { emoji: '🍓', name: '草莓', keywords: ['草莓', '水果', '红色'] },
      { emoji: '🫐', name: '蓝莓', keywords: ['蓝莓', '水果', '蓝色'] },
      { emoji: '🥝', name: '猕猴桃', keywords: ['猕猴桃', '水果', '绿色'] },
      { emoji: '🍅', name: '番茄', keywords: ['番茄', '蔬菜', '红色'] },
      { emoji: '🫒', name: '橄榄', keywords: ['橄榄', '蔬菜', '绿色'] },
      { emoji: '🥥', name: '椰子', keywords: ['椰子', '水果', '热带'] },
      { emoji: '🥑', name: '牛油果', keywords: ['牛油果', '水果', '绿色'] },
      { emoji: '🍆', name: '茄子', keywords: ['茄子', '蔬菜', '紫色'] },
      { emoji: '🥔', name: '土豆', keywords: ['土豆', '蔬菜', '淀粉'] },
      { emoji: '🥕', name: '胡萝卜', keywords: ['胡萝卜', '蔬菜', '橙色'] },
      { emoji: '🌽', name: '玉米', keywords: ['玉米', '蔬菜', '黄色'] },
      { emoji: '🌶️', name: '辣椒', keywords: ['辣椒', '蔬菜', '辣'] },
      { emoji: '🫑', name: '甜椒', keywords: ['甜椒', '蔬菜', '绿色'] },
      { emoji: '🥒', name: '黄瓜', keywords: ['黄瓜', '蔬菜', '绿色'] },
      { emoji: '🥬', name: '绿叶菜', keywords: ['蔬菜', '绿色', '健康'] },
      { emoji: '🥦', name: '西兰花', keywords: ['西兰花', '蔬菜', '绿色'] },
      { emoji: '🧄', name: '大蒜', keywords: ['大蒜', '蔬菜', '辣'] },
      { emoji: '🧅', name: '洋葱', keywords: ['洋葱', '蔬菜', '辣'] },
      { emoji: '🍄', name: '蘑菇', keywords: ['蘑菇', '蔬菜', '菌类'] },
      { emoji: '🥜', name: '花生', keywords: ['花生', '坚果', '小吃'] },
      { emoji: '🫘', name: '豆子', keywords: ['豆子', '蔬菜', '蛋白质'] },
      { emoji: '🌰', name: '栗子', keywords: ['栗子', '坚果', '秋天'] },
      { emoji: '🍞', name: '面包', keywords: ['面包', '食物', '早餐'] },
      { emoji: '🥐', name: '羊角面包', keywords: ['羊角面包', '面包', '法式'] },
      { emoji: '🥖', name: '法棍', keywords: ['法棍', '面包', '法式'] },
      { emoji: '🫓', name: '扁面包', keywords: ['扁面包', '面包', '食物'] },
      { emoji: '🥨', name: '椒盐卷饼', keywords: ['椒盐卷饼', '面包', '德国'] },
      { emoji: '🥯', name: '贝果', keywords: ['贝果', '面包', '早餐'] },
      { emoji: '🥞', name: '煎饼', keywords: ['煎饼', '食物', '早餐'] },
      { emoji: '🧇', name: '华夫饼', keywords: ['华夫饼', '食物', '早餐'] },
      { emoji: '🧀', name: '奶酪', keywords: ['奶酪', '食物', '牛奶'] },
      { emoji: '🍖', name: '肉', keywords: ['肉', '食物', '蛋白质'] },
      { emoji: '🍗', name: '鸡腿', keywords: ['鸡肉', '肉', '食物'] },
      { emoji: '🥩', name: '牛排', keywords: ['牛排', '肉', '食物'] },
      { emoji: '🥓', name: '培根', keywords: ['培根', '肉', '早餐'] },
      { emoji: '🍔', name: '汉堡', keywords: ['汉堡', '食物', '快餐'] },
      { emoji: '🍟', name: '薯条', keywords: ['薯条', '食物', '快餐'] },
      { emoji: '🍕', name: '披萨', keywords: ['披萨', '食物', '意大利'] },
      { emoji: '🌭', name: '热狗', keywords: ['热狗', '食物', '快餐'] },
      { emoji: '🥪', name: '三明治', keywords: ['三明治', '食物', '午餐'] },
      { emoji: '🌮', name: '玉米卷', keywords: ['玉米卷', '食物', '墨西哥'] },
      { emoji: '🌯', name: '墨西哥卷', keywords: ['墨西哥卷', '食物', '墨西哥'] },
      { emoji: '🫔', name: '墨西哥粽', keywords: ['墨西哥粽', '食物', '墨西哥'] },
      { emoji: '🥙', name: '烤肉卷', keywords: ['烤肉卷', '食物', '中东'] },
      { emoji: '🧆', name: '炸豆丸子', keywords: ['炸豆丸子', '食物', '中东'] },
      { emoji: '🥚', name: '蛋', keywords: ['蛋', '食物', '早餐'] },
      { emoji: '🍳', name: '煎蛋', keywords: ['煎蛋', '食物', '早餐'] },
      { emoji: '🥘', name: '一锅炖', keywords: ['一锅炖', '食物', '锅'] },
      { emoji: '🍲', name: '火锅', keywords: ['火锅', '食物', '汤'] },
      { emoji: '🫕', name: '奶酪火锅', keywords: ['奶酪火锅', '食物', '瑞士'] },
      { emoji: '🥣', name: '碗', keywords: ['碗', '食物', '汤'] },
      { emoji: '🍜', name: '面条', keywords: ['面条', '食物', '亚洲'] },
      { emoji: '🍝', name: '意大利面', keywords: ['意大利面', '食物', '意大利'] },
      { emoji: '🍠', name: '烤红薯', keywords: ['红薯', '食物', '烤'] },
      { emoji: '🍢', name: '关东煮', keywords: ['关东煮', '食物', '亚洲'] },
      { emoji: '🍣', name: '寿司', keywords: ['寿司', '食物', '日本'] },
      { emoji: '🍤', name: '炸虾', keywords: ['虾', '食物', '炸'] },
      { emoji: '🍱', name: '便当', keywords: ['便当', '食物', '日本'] },
      { emoji: '🍙', name: '饭团', keywords: ['饭团', '食物', '日本'] },
      { emoji: '🍚', name: '米饭', keywords: ['米饭', '食物', '亚洲'] },
      { emoji: '🍛', name: '咖喱', keywords: ['咖喱', '食物', '印度'] },
      { emoji: '🍥', name: '鱼糕', keywords: ['鱼糕', '食物', '日本'] },
      { emoji: '🥮', name: '月饼', keywords: ['月饼', '食物', '中国'] },
      { emoji: '🍡', name: '团子', keywords: ['团子', '食物', '日本'] },
      { emoji: '🥟', name: '饺子', keywords: ['饺子', '食物', '中国'] },
      { emoji: '🦪', name: '牡蛎', keywords: ['牡蛎', '海鲜', '食物'] },
      { emoji: '🍦', name: '冰淇淋', keywords: ['冰淇淋', '甜点', '冷'] },
      { emoji: '🍧', name: '刨冰', keywords: ['刨冰', '甜点', '冷'] },
      { emoji: '🍨', name: '冰淇淋', keywords: ['冰淇淋', '甜点', '冷'] },
      { emoji: '🍩', name: '甜甜圈', keywords: ['甜甜圈', '甜点', '甜'] },
      { emoji: '🍪', name: '饼干', keywords: ['饼干', '甜点', '甜'] },
      { emoji: '🎂', name: '生日蛋糕', keywords: ['生日蛋糕', '甜点', '生日'] },
      { emoji: '🍰', name: '蛋糕', keywords: ['蛋糕', '甜点', '甜'] },
      { emoji: '🧁', name: '杯子蛋糕', keywords: ['杯子蛋糕', '甜点', '甜'] },
      { emoji: '🥧', name: '派', keywords: ['派', '甜点', '甜'] },
      { emoji: '🍫', name: '巧克力', keywords: ['巧克力', '甜点', '甜'] },
      { emoji: '🍬', name: '糖果', keywords: ['糖果', '甜点', '甜'] },
      { emoji: '🍭', name: '棒棒糖', keywords: ['棒棒糖', '甜点', '甜'] },
      { emoji: '🍮', name: '布丁', keywords: ['布丁', '甜点', '甜'] },
      { emoji: '🍯', name: '蜂蜜', keywords: ['蜂蜜', '甜', '蜜蜂'] },
      { emoji: '🍼', name: '奶瓶', keywords: ['牛奶', '婴儿', '喝'] },
      { emoji: '🥛', name: '牛奶', keywords: ['牛奶', '喝', '乳制品'] },
      { emoji: '☕', name: '咖啡', keywords: ['咖啡', '喝', '提神'] },
      { emoji: '🫖', name: '茶壶', keywords: ['茶', '喝', '茶壶'] },
      { emoji: '🍵', name: '茶', keywords: ['茶', '喝', '日本'] },
      { emoji: '🍶', name: '清酒', keywords: ['清酒', '喝', '日本'] },
      { emoji: '🍾', name: '开瓶', keywords: ['香槟', '喝', '庆祝'] },
      { emoji: '🍷', name: '红酒', keywords: ['红酒', '喝', '葡萄酒'] },
      { emoji: '🍸', name: '鸡尾酒', keywords: ['鸡尾酒', '喝', '派对'] },
      { emoji: '🍹', name: '热带饮料', keywords: ['热带饮料', '喝', '果汁'] },
      { emoji: '🍺', name: '啤酒', keywords: ['啤酒', '喝', '派对'] },
      { emoji: '🍻', name: '碰杯', keywords: ['碰杯', '喝', '庆祝'] },
      { emoji: '🥂', name: '碰杯', keywords: ['碰杯', '喝', '庆祝'] },
      { emoji: '🥃', name: '威士忌', keywords: ['威士忌', '喝', '酒精'] },
      { emoji: '🫗', name: '倒酒', keywords: ['倒酒', '喝', '液体'] },
      { emoji: '🥤', name: '杯子', keywords: ['杯子', '喝', '饮料'] },
      { emoji: '🧋', name: '珍珠奶茶', keywords: ['珍珠奶茶', '喝', '台湾'] },
      { emoji: '🧃', name: '饮料盒', keywords: ['饮料盒', '喝', '果汁'] },
      { emoji: '🧉', name: '马黛茶', keywords: ['马黛茶', '喝', '南美'] },
      { emoji: '🧊', name: '冰块', keywords: ['冰块', '冷', '水'] },
      { emoji: '🥢', name: '筷子', keywords: ['筷子', '餐具', '亚洲'] },
      { emoji: '🍽️', name: '餐具', keywords: ['餐具', '盘子', '刀叉'] },
      { emoji: '🍴', name: '刀叉', keywords: ['刀叉', '餐具', '吃'] },
      { emoji: '🥄', name: '勺子', keywords: ['勺子', '餐具', '喝汤'] },
      { emoji: '🔪', name: '菜刀', keywords: ['菜刀', '刀具', '切'] },
      { emoji: '🫙', name: '罐子', keywords: ['罐子', '容器', '保存'] },
      { emoji: '🏺', name: '陶罐', keywords: ['陶罐', '容器', '古老'] },
    ],
  },
  {
    id: 'objects',
    name: '物体',
    emojis: [
      { emoji: '⌚', name: '手表', keywords: ['手表', '时间', '科技'] },
      { emoji: '📱', name: '手机', keywords: ['手机', '电话', '科技'] },
      { emoji: '💻', name: '电脑', keywords: ['电脑', '笔记本', '科技'] },
      { emoji: '🖥️', name: '台式电脑', keywords: ['台式电脑', '电脑', '科技'] },
      { emoji: '🖨️', name: '打印机', keywords: ['打印机', '办公', '科技'] },
      { emoji: '⌨️', name: '键盘', keywords: ['键盘', '打字', '电脑'] },
      { emoji: '🖱️', name: '鼠标', keywords: ['鼠标', '电脑', '科技'] },
      { emoji: '🖲️', name: '轨迹球', keywords: ['轨迹球', '电脑', '科技'] },
      { emoji: '💽', name: '软盘', keywords: ['软盘', '存储', '科技'] },
      { emoji: '💾', name: '软盘', keywords: ['软盘', '存储', '科技'] },
      { emoji: '💿', name: '光盘', keywords: ['光盘', '存储', '音乐'] },
      { emoji: '📀', name: 'DVD', keywords: ['DVD', '光盘', '电影'] },
      { emoji: '🧮', name: '算盘', keywords: ['算盘', '计算', '古老'] },
      { emoji: '🎥', name: '电影摄像机', keywords: ['电影摄像机', '视频', '记录'] },
      { emoji: '🎞️', name: '电影胶片', keywords: ['电影胶片', '电影', '视频'] },
      { emoji: '📽️', name: '电影放映机', keywords: ['电影放映机', '电影', '视频'] },
      { emoji: '🎬', name: '场记板', keywords: ['场记板', '电影', '导演'] },
      { emoji: '📺', name: '电视', keywords: ['电视', '视频', '看'] },
      { emoji: '📷', name: '相机', keywords: ['相机', '拍照', '照片'] },
      { emoji: '📸', name: '闪光灯', keywords: ['闪光灯', '相机', '拍照'] },
      { emoji: '📹', name: '摄像机', keywords: ['摄像机', '视频', '记录'] },
      { emoji: '📼', name: '录像带', keywords: ['录像带', '视频', '存储'] },
      { emoji: '💿', name: '光盘', keywords: ['光盘', '存储', '音乐'] },
      { emoji: '🔍', name: '放大镜', keywords: ['放大镜', '搜索', '看'] },
      { emoji: '🔎', name: '放大镜', keywords: ['放大镜', '搜索', '看'] },
      { emoji: '🕯️', name: '蜡烛', keywords: ['蜡烛', '光', '火'] },
      { emoji: '💡', name: '灯泡', keywords: ['灯泡', '想法', '光'] },
      { emoji: '🔦', name: '手电筒', keywords: ['手电筒', '光', '照明'] },
      { emoji: '🏮', name: '红灯笼', keywords: ['红灯笼', '光', '中国'] },
      { emoji: '🪔', name: '油灯', keywords: ['油灯', '光', '古老'] },
      { emoji: '✨', name: '闪光', keywords: ['闪光', '星星', '魔法'] },
      { emoji: '🌟', name: '闪烁', keywords: ['闪烁', '星星', '光'] },
      { emoji: '💫', name: '头晕', keywords: ['头晕', '星星', '旋转'] },
      { emoji: '🕳️', name: '洞', keywords: ['洞', '黑', '空'] },
      { emoji: '💣', name: '炸弹', keywords: ['炸弹', '爆炸', '危险'] },
      { emoji: '🧨', name: '鞭炮', keywords: ['鞭炮', '爆炸', '庆祝'] },
      { emoji: '💥', name: '爆炸', keywords: ['爆炸', '炸弹', '冲击'] },
      { emoji: '💫', name: '头晕', keywords: ['头晕', '星星', '旋转'] },
      { emoji: '💦', name: '汗滴', keywords: ['汗滴', '汗', '水'] },
      { emoji: '💨', name: '风', keywords: ['风', '快', '空气'] },
      { emoji: '🕸️', name: '蜘蛛网', keywords: ['蜘蛛网', '蜘蛛', '网'] },
      { emoji: '💫', name: '头晕', keywords: ['头晕', '星星', '旋转'] },
      { emoji: '🔮', name: '水晶球', keywords: ['水晶球', '魔法', '未来'] },
      { emoji: '📿', name: '念珠', keywords: ['念珠', '祈祷', '宗教'] },
      { emoji: '💎', name: '钻石', keywords: ['钻石', '珠宝', '贵重'] },
      { emoji: '🔯', name: '六角星', keywords: ['六角星', '犹太', '宗教'] },
      { emoji: '🪬', name: '法蒂玛之手', keywords: ['法蒂玛之手', '护身符', '保护'] },
      { emoji: '🧿', name: '邪眼', keywords: ['邪眼', '护身符', '保护'] },
      { emoji: '💈', name: '理发店转灯', keywords: ['理发店', '头发', '剪'] },
      { emoji: '⚗️', name: '蒸馏器', keywords: ['蒸馏器', '科学', '化学'] },
      { emoji: '🔭', name: '望远镜', keywords: ['望远镜', '太空', '看'] },
      { emoji: '🔬', name: '显微镜', keywords: ['显微镜', '科学', '小'] },
      { emoji: '🔮', name: '水晶球', keywords: ['水晶球', '魔法', '未来'] },
      { emoji: '🧪', name: '试管', keywords: ['试管', '科学', '化学'] },
      { emoji: '🧫', name: '培养皿', keywords: ['培养皿', '科学', '生物'] },
      { emoji: '🔬', name: '显微镜', keywords: ['显微镜', '科学', '小'] },
      { emoji: '🔭', name: '望远镜', keywords: ['望远镜', '太空', '看'] },
      { emoji: '📡', name: '卫星天线', keywords: ['卫星天线', '通讯', '信号'] },
      { emoji: '💉', name: '注射器', keywords: ['注射器', '医疗', '针'] },
      { emoji: '💊', name: '药丸', keywords: ['药丸', '医疗', '药'] },
      { emoji: '🩹', name: '创可贴', keywords: ['创可贴', '医疗', '伤口'] },
      { emoji: '🩺', name: '听诊器', keywords: ['听诊器', '医疗', '医生'] },
      { emoji: '🪚', name: '横锯', keywords: ['横锯', '工具', '木工'] },
      { emoji: '🔧', name: '扳手', keywords: ['扳手', '工具', '修理'] },
      { emoji: '🔩', name: '螺丝', keywords: ['螺丝', '工具', '金属'] },
      { emoji: '🪛', name: '螺丝刀', keywords: ['螺丝刀', '工具', '修理'] },
      { emoji: '🔨', name: '锤子', keywords: ['锤子', '工具', '打'] },
      { emoji: '⚒️', name: '锤子', keywords: ['锤子', '工具', '打'] },
      { emoji: '🛠️', name: '工具', keywords: ['工具', '修理', '建设'] },
      { emoji: '⌛', name: '沙漏', keywords: ['沙漏', '时间', '等待'] },
      { emoji: '⏳', name: '沙漏', keywords: ['沙漏', '时间', '等待'] },
      { emoji: '⌚', name: '手表', keywords: ['手表', '时间', '科技'] },
      { emoji: '⏰', name: '闹钟', keywords: ['闹钟', '时间', '醒'] },
      { emoji: '🕛', name: '时钟', keywords: ['时钟', '时间', '12点'] },
      { emoji: '🕧', name: '时钟', keywords: ['时钟', '时间', '12点半'] },
      { emoji: '🕐', name: '时钟', keywords: ['时钟', '时间', '1点'] },
      { emoji: '🕜', name: '时钟', keywords: ['时钟', '时间', '1点半'] },
      { emoji: '🕑', name: '时钟', keywords: ['时钟', '时间', '2点'] },
      { emoji: '🕝', name: '时钟', keywords: ['时钟', '时间', '2点半'] },
      { emoji: '🕒', name: '时钟', keywords: ['时钟', '时间', '3点'] },
      { emoji: '🕞', name: '时钟', keywords: ['时钟', '时间', '3点半'] },
      { emoji: '🕓', name: '时钟', keywords: ['时钟', '时间', '4点'] },
      { emoji: '🕟', name: '时钟', keywords: ['时钟', '时间', '4点半'] },
      { emoji: '🕔', name: '时钟', keywords: ['时钟', '时间', '5点'] },
      { emoji: '🕠', name: '时钟', keywords: ['时钟', '时间', '5点半'] },
      { emoji: '🕕', name: '时钟', keywords: ['时钟', '时间', '6点'] },
      { emoji: '🕡', name: '时钟', keywords: ['时钟', '时间', '6点半'] },
      { emoji: '🕖', name: '时钟', keywords: ['时钟', '时间', '7点'] },
      { emoji: '🕢', name: '时钟', keywords: ['时钟', '时间', '7点半'] },
      { emoji: '🕗', name: '时钟', keywords: ['时钟', '时间', '8点'] },
      { emoji: '🕣', name: '时钟', keywords: ['时钟', '时间', '8点半'] },
      { emoji: '🕘', name: '时钟', keywords: ['时钟', '时间', '9点'] },
      { emoji: '🕤', name: '时钟', keywords: ['时钟', '时间', '9点半'] },
      { emoji: '🕙', name: '时钟', keywords: ['时钟', '时间', '10点'] },
      { emoji: '🕥', name: '时钟', keywords: ['时钟', '时间', '10点半'] },
      { emoji: '🕚', name: '时钟', keywords: ['时钟', '时间', '11点'] },
      { emoji: '🕦', name: '时钟', keywords: ['时钟', '时间', '11点半'] },
      { emoji: '🌑', name: '新月', keywords: ['月亮', '新月', '夜晚'] },
      { emoji: '🌒', name: '蛾眉月', keywords: ['月亮', '蛾眉月', '夜晚'] },
      { emoji: '🌓', name: '上弦月', keywords: ['月亮', '上弦月', '夜晚'] },
      { emoji: '🌔', name: '盈凸月', keywords: ['月亮', '盈凸月', '夜晚'] },
      { emoji: '🌕', name: '满月', keywords: ['月亮', '满月', '夜晚'] },
      { emoji: '🌖', name: '亏凸月', keywords: ['月亮', '亏凸月', '夜晚'] },
      { emoji: '🌗', name: '下弦月', keywords: ['月亮', '下弦月', '夜晚'] },
      { emoji: '🌘', name: '残月', keywords: ['月亮', '残月', '夜晚'] },
      { emoji: '🌙', name: '新月', keywords: ['月亮', '新月', '夜晚'] },
      { emoji: '🌚', name: '月亮脸', keywords: ['月亮', '脸', '夜晚'] },
      { emoji: '🌛', name: '新月脸', keywords: ['月亮', '脸', '夜晚'] },
      { emoji: '🌜', name: '新月脸', keywords: ['月亮', '脸', '夜晚'] },
      { emoji: '🌡️', name: '温度计', keywords: ['温度计', '温度', '热'] },
      { emoji: '🌤️', name: '晴间多云', keywords: ['天气', '太阳', '云'] },
      { emoji: '☀️', name: '太阳', keywords: ['太阳', '天气', '热'] },
      { emoji: '🌝', name: '满月脸', keywords: ['月亮', '脸', '满月'] },
      { emoji: '🌞', name: '太阳脸', keywords: ['太阳', '脸', '热'] },
      { emoji: '⭐', name: '星星', keywords: ['星星', '光', '夜晚'] },
      { emoji: '🌟', name: '闪烁星星', keywords: ['星星', '闪烁', '光'] },
      { emoji: '🌠', name: '流星', keywords: ['流星', '星星', '许愿'] },
      { emoji: '🌌', name: '银河', keywords: ['银河', '太空', '星星'] },
      { emoji: '☀️', name: '太阳', keywords: ['太阳', '天气', '热'] },
      { emoji: '🌝', name: '满月脸', keywords: ['月亮', '脸', '满月'] },
      { emoji: '🌞', name: '太阳脸', keywords: ['太阳', '脸', '热'] },
      { emoji: '⭐', name: '星星', keywords: ['星星', '光', '夜晚'] },
      { emoji: '🌟', name: '闪烁星星', keywords: ['星星', '闪烁', '光'] },
      { emoji: '🌠', name: '流星', keywords: ['流星', '星星', '许愿'] },
      { emoji: '🌌', name: '银河', keywords: ['银河', '太空', '星星'] },
      { emoji: '🌤️', name: '晴间多云', keywords: ['天气', '太阳', '云'] },
      { emoji: '☀️', name: '太阳', keywords: ['太阳', '天气', '热'] },
      { emoji: '🌝', name: '满月脸', keywords: ['月亮', '脸', '满月'] },
      { emoji: '🌞', name: '太阳脸', keywords: ['太阳', '脸', '热'] },
      { emoji: '⭐', name: '星星', keywords: ['星星', '光', '夜晚'] },
      { emoji: '🌟', name: '闪烁星星', keywords: ['星星', '闪烁', '光'] },
      { emoji: '🌠', name: '流星', keywords: ['流星', '星星', '许愿'] },
      { emoji: '🌌', name: '银河', keywords: ['银河', '太空', '星星'] },
    ],
  },
];

export const getAllEmojis = (): EmojiItem[] => {
  return emojiCategories.flatMap((category) => category.emojis);
};

export const searchEmojis = (query: string): EmojiItem[] => {
  const lowerQuery = query.toLowerCase();
  if (!lowerQuery.trim()) return [];

  return getAllEmojis().filter((emoji) => {
    return (
      emoji.name.toLowerCase().includes(lowerQuery) ||
      emoji.keywords.some((keyword) => keyword.toLowerCase().includes(lowerQuery))
    );
  });
};
